### ISSUE TITLE
Issues with Docker Build with 1.8.0_191

### ISSUE THREAD

**Issue by rajatumrao** [appropriate/docker-jetty#100]
Seeing below error:

java.lang.IllegalStateException: Cannot read file: modules/alpn-impl/alpn-1.8.0_191.mod
	at org.eclipse.jetty.start.Modules.registerModule(Modules.java:202)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:355)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:360)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
	at org.eclipse.jetty.start.Modules.enable(Modules.java:286)
	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:129)
	at org.eclipse.jetty.start.Main.start(Main.java:435)
	at org.eclipse.jetty.start.Main.main(Main.java:77)

When are we expecting 9.4.13 to be released

**Comment by md5** [comment]
This is solved by #99, which was just merged and will soon push to Docker Hub

**Comment by rajatumrao** [comment]
Thanks a lot. Expecting new image soon
