### ISSUE TITLE
Not able to enable http2 in latest image

### ISSUE THREAD

**Issue by emillundstrm** [appropriate/docker-jetty#22]
Using the command

```
RUN java -jar /usr/local/jetty/start.jar --add-to-startd=http2 --approve-all-licenses
```

in a Dockerfile based on the latest image complains with the following error:

```
org.eclipse.jetty.start.graph.GraphException: Missing referenced dependency: alpn-impl/alpn-1.8.0_66
    at org.eclipse.jetty.start.graph.Graph.selectNodes(Graph.java:470)
    at org.eclipse.jetty.start.graph.Graph.selectNode(Graph.java:447)
    at org.eclipse.jetty.start.graph.Graph.selectNode(Graph.java:415)
    at org.eclipse.jetty.start.graph.Graph.selectNodes(Graph.java:473)
    at org.eclipse.jetty.start.graph.Graph.selectNode(Graph.java:447)
    at org.eclipse.jetty.start.graph.Graph.selectNode(Graph.java:415)
    at org.eclipse.jetty.start.graph.Graph.selectNodes(Graph.java:473)
    at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:151)
    at org.eclipse.jetty.start.Main.start(Main.java:407)
    at org.eclipse.jetty.start.Main.main(Main.java:75)

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information
```

Which I believe is because there is no alpn-1.8.0_66 file in the /usr/local/jetty/modules/alpn-impl/ folder. I was able to get further by symlinking alpn-1.8.0_60 to alpn-1.8.0_66, but this does not seem ideal.

**Comment by md5** [comment]
@joakime @gregw Any chance there's a new Jetty release coming soon that might fix this?

Looking at the downloads page, it looks like 9.3.6 was released a couple weeks ago, but I didn't see an announcement on `jetty-announce` :cry:

**Comment by md5** [comment]
I just pushed a commit to update to 9.2.14 and 9.3.6: https://github.com/appropriate/docker-jetty/commit/072c632652b4c13ceb78db302411d57d612086b9

I'm a bit busy at the moment, so I'll let Travis build those and see what we get.

**Comment by md5** [comment]
I checked the 9.3.6 image and I see a `alpn-1.8.0_66.mod` file. I also see that the tests are passing for my updates, so I've submitted a request to release a new official image for `jetty` versions 9.2 and 9.3: https://github.com/docker-library/official-images/pull/1220

**Comment by md5** [comment]
@emillundstrm The 9.3.6 image is now on Docker Hub, although the supported tags in the docs are not yet updated.

Please give it a try and reopen this issue if you're still having problems. Thanks!

**Comment by emillundstrm** [comment]
I can confirm that it works now. Thanks!

**Comment by md5** [comment]
:+1:
