### ISSUE TITLE
http/2, alpn setup failure

### ISSUE THREAD

**Issue by urandom2** [appropriate/docker-jetty#90]
The [HTTP/2 Support](https://hub.docker.com/_/jetty/) instructions are currently failing with images based on `9.4.9.v20180320` based images (`jetty:latest`, `jetty:alpine`):
```
$ docker build .
Sending build context to Docker daemon  186.7MB
Step 1/3 : FROM jetty:alpine
 ---> 6c074c65bd67
Step 2/3 : RUN java -jar "$JETTY_HOME/start.jar" --create-startd --add-to-start="http2" --approve-all-licenses
 ---> Running in 8e7a9a2ef816
java.lang.IllegalStateException: Cannot read file: modules/alpn-impl/alpn-1.8.0_171.mod
        at org.eclipse.jetty.start.Modules.registerModule(Modules.java:202)
        at org.eclipse.jetty.start.Modules.enable(Modules.java:355)
        at org.eclipse.jetty.start.Modules.enable(Modules.java:360)
        at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
        at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
        at org.eclipse.jetty.start.Modules.enable(Modules.java:286)
        at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:127)
        at org.eclipse.jetty.start.Main.start(Main.java:435)
        at org.eclipse.jetty.start.Main.main(Main.java:77)

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
The command '/bin/sh -c java -jar "$JETTY_HOME/start.jar" --create-startd --add-to-start="http2" --approve-all-licenses' returned a non-zero code: 247
```
Should these instructions be updated, or is there a larger failure occurring?

**Comment by md5** [comment]
That happens when the JRE/JDK version being used does not yet have a `*.mod` file in the Jetty installation being used. I believe this should be fixed by #91, once it makes it to Docker Hub

**Comment by md5** [comment]
Docker Hub update is being tracked in https://github.com/docker-library/official-images/pull/4498

**Comment by md5** [comment]
Should be fixed by the latest push
