### ISSUE TITLE
start.jar explodes: missing/invalid file modules/alpn-impl/alpn-1.8.0_181.mod

### ISSUE THREAD

**Issue by draeath** [appropriate/docker-jetty#94]
I'm receiving this from the `jetty:9-jre8` tag, which I just pulled a few minutes ago. Image ID in 'docker image ls' is `07b6d9a3f5d2`

```
12:28:20.805 Step 14/19 : RUN java -jar ${JETTY_HOME}/start.jar --add-to-start=https,http2 --approve-all-licenses
12:28:20.805  ---> Running in 665b7b212c45
12:28:20.805 java.lang.IllegalStateException: Cannot read file: modules/alpn-impl/alpn-1.8.0_181.mod
12:28:20.805 	at org.eclipse.jetty.start.Modules.registerModule(Modules.java:202)
12:28:20.805 	at org.eclipse.jetty.start.Modules.enable(Modules.java:355)
12:28:20.805 	at org.eclipse.jetty.start.Modules.enable(Modules.java:360)
12:28:20.805 	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
12:28:20.805 	at org.eclipse.jetty.start.Modules.enable(Modules.java:377)
12:28:20.805 	at org.eclipse.jetty.start.Modules.enable(Modules.java:286)
12:28:20.805 	at org.eclipse.jetty.start.BaseBuilder.build(BaseBuilder.java:129)
12:28:20.805 	at org.eclipse.jetty.start.Main.start(Main.java:435)
12:28:20.805 	at org.eclipse.jetty.start.Main.main(Main.java:77)
12:28:20.805 
12:28:20.805 Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
12:28:20.805        java -jar $JETTY_HOME/start.jar --help  # for more information
```

**Comment by draeath** [comment]
Seems related to #90 and #91 - appears it never made it to Dockerhub (or the fix didn't work)

**Comment by draeath** [comment]
`jetty:9.4.9-jre8` and `jetty:9.3-jre8` have this problem as well.

**Comment by draeath** [comment]
Looks like this is an upstream jetty issue. an ALPN for jdk8 u181 does not exist in the distributable tgz.

**Comment by draeath** [comment]
Reported upstream. https://github.com/eclipse/jetty.project/issues/2819
